// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tarefas.Infrastructure.Data;

#nullable disable

namespace Tarefas.Infrastructure.Migrations
{
    [DbContext(typeof(TarefasDbContext))]
    [Migration("20250930005804_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Tarefas.Domain.Entities.Tarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Concluida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasComment("Indica se a tarefa foi concluída");

                    b.Property<DateTime>("DataAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')")
                        .HasComment("Data da última atualização");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')")
                        .HasComment("Data de criação da tarefa");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("TEXT")
                        .HasComment("Data da exclusão lógica");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasComment("Descrição detalhada da tarefa");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasComment("Soft delete flag");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasComment("Título da tarefa");

                    b.HasKey("Id");

                    b.HasIndex("Concluida")
                        .HasDatabaseName("IX_Tarefas_Concluida");

                    b.HasIndex("DataCriacao")
                        .HasDatabaseName("IX_Tarefas_DataCriacao");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Tarefas_IsDeleted");

                    b.HasIndex("Concluida", "IsDeleted")
                        .HasDatabaseName("IX_Tarefas_Concluida_IsDeleted");

                    b.ToTable("Tarefas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Concluida = true,
                            DataAtualizacao = new DateTime(2025, 9, 29, 0, 58, 2, 962, DateTimeKind.Utc).AddTicks(9486),
                            DataCriacao = new DateTime(2025, 9, 23, 0, 58, 2, 962, DateTimeKind.Utc).AddTicks(8622),
                            Descricao = "Criar endpoints para CRUD de tarefas usando Clean Architecture",
                            IsDeleted = false,
                            Titulo = "Implementar API REST"
                        },
                        new
                        {
                            Id = 2,
                            Concluida = false,
                            DataAtualizacao = new DateTime(2025, 9, 27, 0, 58, 2, 963, DateTimeKind.Utc).AddTicks(876),
                            DataCriacao = new DateTime(2025, 9, 27, 0, 58, 2, 963, DateTimeKind.Utc).AddTicks(873),
                            Descricao = "Adicionar EF Core com SQLite para persistência de dados",
                            IsDeleted = false,
                            Titulo = "Configurar Entity Framework"
                        },
                        new
                        {
                            Id = 3,
                            Concluida = true,
                            DataAtualizacao = new DateTime(2025, 9, 29, 22, 58, 2, 963, DateTimeKind.Utc).AddTicks(942),
                            DataCriacao = new DateTime(2025, 9, 25, 0, 58, 2, 963, DateTimeKind.Utc).AddTicks(940),
                            Descricao = "Criar testes unitários e de integração abrangentes",
                            IsDeleted = false,
                            Titulo = "Implementar Testes"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
